### ISSUE TITLE
Support inlined frames in the stack walker

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/rust-minidump#239]
Breakpad introduced support for inlined functions and frames in revision [f0803507](https://chromium.googlesource.com/breakpad/breakpad/+/f0803507950279bd1e48d05f5fb4b4377c2917f7). Once we've got full support for stack unwinding using traditional Breakpad CFI we should support this too.

**Comment by Gankra** [comment]
I'm demoting this to "cool dream" because it increasingly sounds like this whole thing is a mess upstream, so it's not obvious what implementing this even means.

**Comment by mstange** [comment]
This was fixed in #599 and #635. Somebody with the appropriate privileges can close this issue.
