### ISSUE TITLE
MinidumpStream::STREAM_TYPE should just be a u32

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#362]
https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump/src/minidump.rs#L103-L113

While it is technically correct that it "should" be a MINIDUMP_STREAM_TYPE, this prevents a user of `minidump` from implementing MinidumpStream for their own custom stream that we have no knowledge of. While this is not a usecase I have put any explicit effort into, it Just Works in our architecture.

This value is literally only coverted to a u32 in our codebase, and if you want the MINIDUMP_STREAM_TYPE it's trivial to convert back from a u32, so there's no advantage to keeping the stronger type safety.

Sentry is interested in doing this for one of their custom streams, although I also wouldn't oppose them upstreaming their impl into rust-minidump (we already support a bunch of Mozilla and Google extensions in-tree, and doing so allows minidump-processor and minidump-stackwalk to handle it). But maybe the flexibility is useful to them.

**Comment by luser** [comment]
Yeah, that seems fine. The only nice thing about having the known values in an enum is preventing us from making a typo and accidentally including a duplicate value, but that's marginal at best.

**Comment by Gankra** [comment]
Note that we should be able to write 

`const STREAM_TYPE: u32 = MINIDUMP_STREAM_TYPE::MY_STREAM as u32;`

So we still get the primary advantages of using the enum in our code.

**Comment by luser** [comment]
Just thinking out loud there. The motivation here is very sensible and I don't feel strongly about any part of the existing design. Even changing the whole thing from an enum to a list of `const WHATEVER_STREAM: u32 = 123;` would be totally fine. (Maybe in a `mod known_streams` or similar?)
