### ISSUE TITLE
Populate the "system_info.cpu_microcode_version" field with the contents of the "CPUMicrocodeVersion" annotation

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/rust-minidump#421]
We extract this field from `/proc/cpuinfo` in Linux minidumps but it's also available in (most) Windows ones as a [crash annotation](https://searchfox.org/mozilla-central/rev/b0c5c3b9821c2f22193fd6e1e9f66032639da1a1/toolkit/crashreporter/CrashAnnotations.yaml#234-237) in the .extra file. The version is stored as a string representing the hexadecimal value starting with the 0x prefix.

**Comment by Gankra** [comment]
Gabriele's reference to the ".extra" file is the mozilla-specific "evil json" file implemented here: https://github.com/luser/rust-minidump/blob/master/minidump-processor/src/evil.rs

Someone at mozilla needs to look up the schema for this field to add support.

But of course I would always prefer that this stuff just gets fed into proper custom minidump streams. Alas, path of least resistance remains evil...

**Comment by gabrielesvelto** [comment]
This was done in PR: https://github.com/rust-minidump/rust-minidump/pull/772
