### ISSUE TITLE
remove "matching debug info" link

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#441]
https://docs.rs/minidump-common/0.9.6/src/minidump_common/format.rs.html#297-299

points to http://www.debuginfo.com/articles/debuginfomatch.html for additional details

Seems it's dead now :(

**Comment by luser** [comment]
Per our conversation on Discord, the Wayback Machine has a copy we could link instead: http://web.archive.org/web/20210227224734/https://www.debuginfo.com/articles/debuginfomatch.html
