### ISSUE TITLE
Drop support for the ThreadIdNameMapping crash annotation (sometimes in 2023)

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/rust-minidump#480]
As part of the work to get rid of the ~~evil JSON~~  separate crash annotations file I've removed the `ThreadIdNameMapping` annotation and made sure that all our minidump writers fill up the thread names list instead (see bug [1756505](https://bugzilla.mozilla.org/show_bug.cgi?id=1756505) on our tracker). It will take a time for the change to flow all the way to the next ESR release so I'm filing this not to forget that we want to get rid of this as soon as possible.

**Comment by jan-auer** [comment]
In the linked bugzilla ticket you're mentioning Minidump writers for all platforms that write the new stream. Are these patches on crashpad or separate writers?

**Comment by gabrielesvelto** [comment]
They're our forked Breakpad writers which I have patched. The macOS one is [here](https://phabricator.services.mozilla.com/D118927) and it also contains the platform-independent machinery to write that stream. The Linux/Android one is [here](https://phabricator.services.mozilla.com/D139318). I think it should be possible to add them to vanilla Breakpad, our fork is not that different from the upstream one. Also I haven't tested them on iOS but given that it shares the kernel machinery with macOS there's a chance the writer would work there too.

**Comment by gabrielesvelto** [comment]
Also to the best of my knowledge Crashpad doesn't support writing those streams.

**Comment by jan-auer** [comment]
Thanks for the pointers! @Swatinem What do you think of implementing this for Crashpad (in our fork for now)?

**Comment by Swatinem** [comment]
You mean writing of thread names?

**Comment by jan-auer** [comment]
Right, into the MinidumpThreadNameList stream, similar to the patches Gabriele linked above. While we're on it, we might as well cherry-pick them into our Breakpad fork, too.
