### ISSUE TITLE
sketch: proper async stackwalking

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#561]
Right now we are async only on paper, and are still fundamentally single-threaded. This is fine because the "production" configuration achieves parallelism through multi-process. However this is suboptimal for two reasons:

* The cache design results in two processes "racing" to download a file and CAS (rename) their copy into the folder. This is needless duplicated work.
* For local usage, this may needlessly serialize downloads when we could be doing many downloads (or loads from disk) in parallel.

One way to make things "proper async" would be to implement the request coalescing design described in this article: https://fasterthanli.me/articles/request-coalescing-in-async-rust

The basic idea would be to:

* for each thread we want to stackwalk, [tokio::task::spawn](https://docs.rs/tokio/latest/tokio/task/fn.spawn.html) the stackwalk so they're all running concurrently (and then join on their completion at the end).
* wrap [the in-memory symbolizer cache results](https://github.com/rust-minidump/rust-minidump/blob/4a60e95fd1fceda67aa61cef85461d65457ab046/breakpad-symbols/src/lib.rs#L472) in a more complex type that can distinguish "not present", "present", and "already downloading" (a new state)
* the "downloading" state would contain [tokio::sync::broadcast](https://docs.rs/tokio/latest/tokio/sync/broadcast/index.html) (an mpmc channel)
  * created by the first task that wants to download it (the whole cache is wrapped in a Mutex so we can make sure only one task sees this state) which would spawn a subtask and itself subscribe to the channel to allow one task to itself spawn multiple downloads, which would be desirable for getting a .exe and .pdb at once
  * everyone else would just subscribe to the channel and wait to be notified of "complete" and then reacquire the cache and get the parsed/processed result
  
In this way I believe we can basically ensure "maximum possible parallelism" without redundant work. However this will completely scramble all our very-useful logging, so we would probably also want to migrate to [tracing](https://docs.rs/tracing/0.1.34/tracing/).

This is a lot of work and it's unclear how big the wins would be (or if they would actually pessimize things!), so I don't plan to implement it any time soon. Sketching it out for anyone who might want it.

**Comment by Swatinem** [comment]
This is a nice writeup, I now had some time looking at this, as we are evaluating async stackwalking right now (so far we only are fully sync).

Here is a couple of high-level notes from my POV:

* Spawning "tasks" via `tokio::task::spawn` kinda locks you in to a very specific executor. Not sure this matters though since pretty much everyone is using tokio anyway nowadays. 🤷🏻‍♂️ 
* Also related to the above and your concern if this might "pessimize things": Spawning tasks (vs simple `join_all` concurrency) is a bit heavy weight, as it requires tasks to be `'static`, which is a huge pain itself and involves `Arc`-ing or `Clone`-ing stuff. On the other hand spawning tasks makes actual CFI evaluation parallel (vs only concurrent).
* The current design of the `SymbolProvider` trait pushes all of the responsibility of request coalescing and caching onto the implementator, which is great, as from the perspective of `process_minidump` you don’t have to care about any if this.
* In Symbolicator, we have our own implementations for request coalescing and on-disk caching/loading. Admittedly that is the ugliest part of symbolicator right now and in desperate need of a redesign, but that is a different story. I just brought that up as an example that our own `SymbolProvider` would do all of this already.

Also I remember back when I originally brought up `async`, I had a completely different architecture in mind really. As async was/is currently implemented, having `walk_frame` be async is a bit too fine-grained IMO.

My original Idea was to split symbol loading (the async part) from cfi walking:

```
trait Module {
    type FrameIter: Iterator<Item = Frame>;

    /// Resolve the caller with CFI information
    fn walk_with_cfi(cpu_context: &CpuContext, stack_memory: Memory) -> CpuContext;

    /// Symbolicate Frames and Inlinees for an instruction address
    fn symbolicate_frame(cpu_context: CpuContext) -> FrameIter;
}

trait SymbolProvider {
    type M: Module;

    async fn resolve_module(module: &ModuleId) -> M;
}
```

Though as I now think about it again, every frame can potentially have a different module, so not sure this makes any difference in practice. Though the API kind of separates the two concerns of loading vs processing which is nice.

Separating out module loading into its own trait/API again would bring up the question if you want to do request coalescing inside of `process_minidump`, or rather delegate that to the implementor of `SymbolProvider`.

**Comment by Gankra** [comment]
So I just learned a crapton about this problem space from @mystor's great work [making cargo-vet properly async](https://github.com/mozilla/cargo-vet/pull/199) (shhh... project not production ready). 

She used primarily `join` instead of my original understanding that everything had to use `spawn+block_on`, so that all of our logic is in fact essentially single-threaded but concurrent, kinda like JS event loops, and so everything can still be passed around by-reference. It now all goes much faster because the main bottleneck on everything is i/o, and that now gets multiplexed. I believe this is the case for minidump-processor as well.

Instead of using complicated channels we use `Arc<`[`OnceCell`](https://docs.rs/tokio/latest/tokio/sync/struct.OnceCell.html)`>` (there's still some Arc and Mutex kicking around just in case we want to go full multi-threaded).

So yeah I think what minidump-processor wants is to join_all on stackwalking all the threads, and then inside of breakpad-symbols (or your implementation) we want something like the CacheState type nika introduced:

```rust
struct CacheState {
    /// Paths for unpacked packages from this version.
    fetched_packages: HashMap<(String, Version), Arc<tokio::sync::OnceCell<PathBuf>>>,
    /// Computed diffstats from this version.
    diffed: HashMap<(String, Delta), Arc<tokio::sync::OnceCell<DiffStat>>>,
}
```

But for us it would be more like

```rust
/// Kinds of files we can care about having available
enum FileKind {
  /// Breakpad sym file
  Sym,
  /// Actual binary (.exe/.so/.dylib)
  Binary,
  /// Extra debuginfo (.pdb)
  Debuginfo,
}

/// Unique set of values that identifies a file we might want
/// (I forget what set of values this can/should be, just a sketch)
type FileKey = (CodeId, DebugId, FileKind);

struct CacheState {
    /// Paths for files we've fetched, may include native binaries
    fetched_files: HashMap<FileKey, Arc<tokio::sync::OnceCell<Result<PathBuf, FetchError>>>>,

    /// Fully parsed and queryable symbols from a .sym file
    parsed_symbols: HashMap<FileKey, Arc<tokio::sync::OnceCell<Result<SymbolFile, SymbolError>>>>,

    /// In the future, some more native repr based on memmap so we can avoid parsing
    /// entire file and use the fact that native debuginfo is kinda random-access?
    native_symbols: HashMap<FileKey,  ???>>
}
```

This would let any of the N stackwalks request and cooperate on fetching+loading+parsing files without having to complicate much of the design.

**Comment by Gankra** [comment]
(See #558 for initial native binary stuff)

**Comment by Gankra** [comment]
I agree that relying on tokio is conceptually totally fine... except I'm not sure what the implications might be for someone who wants to compile to wasm, which we kinda vaguely would like to support but It's Hard and Not A Blocker.

**Comment by Gankra** [comment]
I've iterated a bit closer to this in https://github.com/rust-minidump/rust-minidump/pull/558#issuecomment-1159371208

**Comment by Gankra** [comment]
Building on top of my other inflight PRs, I did a test experiment benchmarking the current published version against a hacked up version that just does `join_all` on the stackwalking as naively as possible:


`socc-pair --bench=3 --clean-cache --api-token=<redacted> --crash-id=`[20824cf2-1dbb-491f-a8c0-8a8000220618](https://crash-stats.mozilla.org/report/index/20824cf2-1dbb-491f-a8c0-8a8000220618)

(~80 threads to stackwalk)

before (no join_all, my local branch):

```
benchmark results (ms):
  6515, 6630, 10591,
average runtime: 00m:07s:912ms (7912ms)
median runtime:  00m:06s:630ms (6630ms)
min runtime:     00m:06s:515ms (6515ms)
max runtime:     00m:10s:591ms (10591ms)
```

after: (join_all, hacked up branch):

```
benchmark results (ms):
  3161, 3195, 3152,
average runtime: 00m:03s:169ms (3169ms)
median runtime:  00m:03s:161ms (3161ms)
min runtime:     00m:03s:152ms (3152ms)
max runtime:     00m:03s:195ms (3195ms)
```

So even doing a completely terrible job at being async (lots of blocking File ops mixed in), having any kind of concurrency at all for the http requests (which are the overwhelming bottleneck on a cold cache)

**Comment by Gankra** [comment]
non-trivialities on async-ifying I noticed:

* The loop in minidump_processor where we stackwalk the threads is currently very bloated with other analysis. Presumably if we want to join_all that, we should try to do as much analysis single-threaded and then have a tighter join_all loop for just the stackwalking

* The tempfile logic for the cache is designed around being safe for multi-process usage, and as such does a lot of "create a tempfile, write to it, rename it into its final location". This is currently done with the tempfile crate (to handle platform-specific particulars of temp/renames) which is purely sync. This is especially unfortunate because we do that temp-file-writing interleaved with the async parser loop where the http downloading happens (parse_async in breakpad-symbols). Ideally we would be able to use tokio::fs::File, but that transform doesn't seem possible/trivial.

* Currently we make semantics guarantees about the order we "try" paths and URLs in, so doing `joins` inside breakpad-symbols is nastier. I think it would be fine to try multiple things in parallel as long as we choose the winner in order. This is already happily supported by `join` except the code is currently structured such that "open a connection, download, parse, write-to-file, swap-file-into-cache" is a single monolithic operation. We need to break the operation up so that at very least the final swap-into-cache is in-order (unclear if we want to prevent the HTTP requests+parses from running).

* There are sync parser paths for Files (SimpleSymbolSupplier) and slices (StringSymbolSupplier) that should ideally be made async. Ideally this would go through async_parse, but that code is fairly hardcoded to Response. It's surprisingly difficult to be abstract over a reqwest::Response and tokio::fs::File 😿. I hacked around this by just wrapping sync parser calls in spawn_blocking.

**Comment by Gankra** [comment]
> Separating out module loading into its own trait/API again would bring up the question if you want to do request coalescing inside of process_minidump, or rather delegate that to the implementor of SymbolProvider.

I'm pretty confident you want it to be a responsibility of SymbolProvider. If you do, you can make a program that has one SymbolProvider and N "instances" of minidump_processor running in parallel, safe in the knowledge that SymbolProvider can handle all the caching/rate-limiting. The only knowledge it theoretically lacks is the current "live" modules that might inform an LRU thing more subtley, but I don't think minidump-processor actually *has* any better insight than SymbolProvider, because it can't really tell what modules will be needed in future frames. The only possible limiting you might want to do inside minidump-processor is "max number of stackwalks" i.e. if you have a crash report with 300 threads, do you really want to join all of those together?

But yeah the weird thing is that each thread's stackwalk is *desperately serial* because every frame has a reasonable chance to hop into another module, but you can't know what module you want until you resolve the previous one completely. However all the threads are *very parallel* in that they don't care what the other one is doing... except if all your threads are in my_program.exe they all need to block on that getting downloaded and parsed. Your parallelism is kinda how many modules you have and how fragmented that is.

This also brings up another potentially concurrency mode that I'm *pretty* sure is a bad idea but here it is nonetheless: before doing *any* stackwalking we could tell the SymbolProvider to start prefetching the symbols for every single module as a background task, and then have all the stackwalks start after that, blocking whenever they need symbols that aren't done downloading/parsing yet. I think this is probably a bad idea because I think most modules never end up getting involved in a stackwalk, so you're doing a lot of wasted speculative work, at least for something as big as Firefox.

**Comment by Swatinem** [comment]
> you can make a program that has one SymbolProvider and N "instances" of minidump_processor running in parallel

Oh absolutely! I completely forgot about that, since we do that anyway in symbolicator in a different layer of our abstraction.

> I think this is probably a bad idea because I think most modules never end up getting involved in a stackwalk, so you're doing a lot of wasted speculative work

Yes. There can potentially be hundreds of modules, but realistically only a couple (main exe, libc) are being used. An older version of symbolicator used a middle ground by doing a stack scan without any kind of CFI to inform it which modules to load, afterwards it did a second stackwalk with CFI for the final result. That resulted in both false positives and false negatives. We changed it to be iterative so right now it runs that in a loop as long as it detects new CFI being needed (and being able to load it), which is also wasteful.

We just recently started moving to the properly async way and noticed through snapshot changes that we still had a few false positives in there. CC @loewenheim

**Comment by Gankra** [comment]
we landed concurrent stackwalking, but not parallel stackwalking. parallel stackwalking would require a pretty major overhaul of `minidump`'s design to make the streams shareable, or some kind of `thread::scoped` like mechanism to let us pass on-stack state in. let's call this fixed for now.
