### ISSUE TITLE
proc maps ranges are not inclusive

### ISSUE THREAD

**Issue by mstange** [rust-minidump/rust-minidump#586]
Today I discovered the range-map code in this repo.
It uses a `Range` type which models an **inclusive** range.

I don't think the code in this repo is very well served by an inclusive range type. I see lots and lots of occurrences of the pattern "end_address - 1".

Here's a place where we *don't* subtract 1 from the end, and I think that's wrong:

https://github.com/rust-minidump/rust-minidump/blob/fd680d28262bc84bdca6c9e4f64f1d3d937f081b/minidump/src/minidump.rs#L2337-L2343

Searching the web for "proc maps" turns up examples such as this one:

```
7faa721ce000-7faa721cf000 r--p 00000000 08:30 3021                       /usr/lib/locale/C.UTF-8/LC_ADDRESS
7faa721cf000-7faa724b5000 r--p 00000000 08:30 3034                       /usr/lib/locale/locale-archive
7faa724b5000-7faa724da000 r--p 00000000 08:30 11971                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

These ranges are consecutive; the end address of one range is equal to the start address of the next range. The ranges don't overlap.

So really I'm suggesting two things in this bug:

 - We should fix the proc maps code, and
 - Inclusive ranges of integers are basically never what you want.

How do people feel about switching to the `rangemap` crate (no dash between "range" and "map")? https://docs.rs/rangemap/

**Comment by gabrielesvelto** [comment]
> How do people feel about switching to the `rangemap` crate (no dash between "range" and "map")? https://docs.rs/rangemap/

Nothing against it from me, anything that makes the codebase easier to read and more robust gets a :+1: from me.

**Comment by Gankra** [comment]
Notes:

breakpad-symbols is soft-forking some of the code here: 

https://searchfox.org/mozilla-central/source/python/mozbuild/mozbuild/vendor/vendor_rust.py#749-753

and also does some manual corrections on overlapping ranges here:

**Comment by mstange** [comment]
Yeah this is turning out to be quite the journey. I'm experimenting with replacing some of the RangeMap uses with Vecs and manual binary search. The overlap heuristics is where I'm having the most trouble deciding what behavior to keep and what to change so that the implementation is simpler. It seems to me that most of these heuristics are just aimed at avoiding panics from range_map, and any way to deal with them is fine. I've opted to just do "sort by address, and then use dedup_by to remove fully-subsumed ranges" but I'm not sure if that's good enough.

**Comment by Gankra** [comment]
My condolences on the rangemap stuff. I too spent a while being like "why the fuck is this like this, I should just rip this all out... ugh no there's weirdness here..."

**Comment by mstange** [comment]
PR is up in #590, please feel free to pick it apart :)
