### ISSUE TITLE
thread names have non-deterministic print order

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#630]
extremely minor but because MinidumpThreadNames just stores a HashMap, if you read it twice and `print` the contents, you get two different results.

This is problematic for `minidump-debugger` because it can result in the `raw dump` view of this stream wildly flickering as it randomly shuffles itself at 60fps 😱! Changing to BTreeMap would make the result properly deterministic/sorted with minimal overhead, since these values are only looked up once per thread.

https://github.com/rust-minidump/rust-minidump/blob/a525b3fe40495680a5c4984f8d1223963583f894/minidump/src/minidump.rs#L306

**Comment by afranchuk** [comment]
This has been fixed.
https://github.com/rust-minidump/rust-minidump/blob/46b7a9ce4809ac089bfd3cb7ced7c9a3974951dd/minidump/src/minidump.rs#L306
