### ISSUE TITLE
registers not printed in json output in places i thought it should be

### ISSUE THREAD

**Issue by willkg** [rust-minidump/rust-minidump#639]
It's a terrible summary, but the gist of it is that I spent today writing a jsonschema for the processed crash in Socorro because reasons when I noticed that the schema [here](https://github.com/rust-minidump/rust-minidump/blob/main/minidump-processor/json-schema.md) suggests there should be registers object at

```
crashing_thread.registers
```

but the rust-minidump stackwalker output puts it at:

```
crashing_thread.frames.[0].registers
```

Also, I expected there to be corresponding registers object at:

```
threads.[crashing_thread].frames.[0].registers
```

because the schema said that the `crashing_thread` object was primarily redundant information.

Anyhow, seems like the spec and the reality are out of sync. I think Socorro ignores register information at the moment, so this is only an issue with my jsonschema thing. Also, this is probably related to #364.

**Comment by Gankra** [comment]
Oops! The current behaviour is definitely the "intended" behaviour, the docs are in the wrong here.

**Comment by Gankra** [comment]
I think I'll move `registers` into the general schema for a stackframe and note that currently this is only set for the first frame, and only in the crashing_thread copy-paste.

**Comment by luser** [comment]
The registers are purely informative (for human consumption), and aside from the ones that are used for stackwalking the crashing thread is really the only place they're interesting. Additionally, registers could potentially contain sensitive information, which is I think the original motivation for sequestering them to the `crashing_thread` subtree.
