### ISSUE TITLE
Detect crashes with inconsistent/impossible crash addresses

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/rust-minidump#704]
A recent Firefox crash spike (bug [1796282](https://bugzilla.mozilla.org/show_bug.cgi?id=1796282)) was caused by a CPU bug. This took a while to figure out as we have only a handful of people within Mozilla that can identify those. However the crashes had an obvious hint that this crash could have been impossible: the disassembled crash address was valid (and not a non-canonical address like it appeared in many crashes) and more importantly it fell within an accessible and readable region of memory, so the crash reason (`EXCEPTION_ACCESS_VIOLATION_READ`) coupled with that address made no sense.

Given we have the memory info list available in each minidump we could detect these instances and flag these crashes as impossible or inconsistent so that they're easier to analyze.

Note that there's more hints of inconsistency that could be detected: `EXCEPTION_ACCESS_VIOLATION_EXEC` crashes in areas that are executable, or `EXCEPTION_ACCESS_VIOLATION_*` crashes when the disassembled instruction doesn't contain any memory accesses (we've seen those in CPU bugs too for example, the crashing instruction was a jump).

**Comment by gcp** [comment]
More examples of "impossible" crashes that this could help detect:

- [Crash when executing `ucomiss` instructions emulating an x86-64 CPU on an AArch64 host](https://gitlab.com/qemu-project/qemu/-/issues/1637)
- [Crash in [@ double_conversion::PowersOfTenCache::GetCachedPowerForBinaryExponentRange] on Gemini Lake-based Atom CPUs](https://bugzilla.mozilla.org/show_bug.cgi?id=1746270)
- [Bug 1796126 - Crashes on AMD Zen 1 (family 23 model 1 stepping 1)](https://bugzilla.mozilla.org/show_bug.cgi?id=1796126)
- [Bug 1863991 - Crash in [@ style::properties::cascade::Cascade::apply_non_prioritary_properties]](https://bugzilla.mozilla.org/show_bug.cgi?id=1863991)
- [Bug 1820832 - Crash in [@ nsIFrame::GetParent]](https://bugzilla.mozilla.org/show_bug.cgi?id=1820832)
