### ISSUE TITLE
Symbol generation alternative to Breakpad?

### ISSUE THREAD

**Issue by ePirat** [rust-minidump/rust-minidump#748]
This is not an issue, just a question but I could not find any other place where to ask this, sorry!

I was wondering if, similar to this.project replacing the minidump handling parts of Breakpad, is there a project that can be used to generate symfiles too or is that still done using Breakpad at Mozilla?

**Comment by mstange** [comment]
Yes, it's at https://github.com/mozilla/dump_syms/

**Comment by ePirat** [comment]
Thanks!
