### ISSUE TITLE
Add LICENSE files to releases of individual crates

### ISSUE THREAD

**Issue by molenzwiebel** [rust-minidump/rust-minidump#756]
Hi there!

In order to give proper attributions for any crates I use, I use the [cargo about](https://github.com/EmbarkStudios/cargo-about) tool. This automatically gathers the licenses for each (transitive) dependency used. This tool is currently failing for all crates in this repository, as the LICENSE file is situated in the root of the repository and is therefore not included in the bundles that are pushed to crates.io.

I've gone ahead and manually elaborated the licenses in my project for now, but it'd be great if you could consider adding the licenses to the releases of the individual packages too. 

Thanks for all the work on rust-minidump!

**Comment by gabrielesvelto** [comment]
I think this might be useful for [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) too.

**Comment by gabrielesvelto** [comment]
Done

**Comment by molenzwiebel** [comment]
Thanks!
