### ISSUE TITLE
clippy is currently unhappy

### ISSUE THREAD

**Issue by luser** [rust-minidump/rust-minidump#777]
I keep getting email notifications about this:
https://github.com/rust-minidump/rust-minidump/actions/runs/3871616616/jobs/6599583626

I'm not sure why clippy is configured for JSON output in CI, it makes the logs pretty hard to read. (Is something supposed to be interpreting that?)

**Comment by afranchuk** [comment]
If I'm not mistaken, https://github.com/rust-minidump/rust-minidump/commit/30d063fb64612b6ef0a2e24e9038219c7ad1d199 addressed this.

**Comment by gabrielesvelto** [comment]
Yes, it should be good now.

**Comment by luser** [comment]
Thanks! Those emails were getting annoying. :)
