### ISSUE TITLE
where is minidump.dmp file?

### ISSUE THREAD

**Issue by anranziruo** [rust-minidump/rust-minidump#790]
minidump-stackwalk --symbols-url=https://symbols.mozilla.org/ /path/to/minidump.dmp,i want to have a try

**Comment by luser** [comment]
That's intended to be an example commandline where you provide your own minidump. If you simply want to try the tools out you can use any of the dump files in the `testdata` folder in this repository:
https://github.com/rust-minidump/rust-minidump/tree/main/testdata

**Comment by anranziruo** [comment]
> That's intended to be an example commandline where you provide your own minidump. If you simply want to try the tools out you can use any of the dump files in the `testdata` folder in this repository: https://github.com/rust-minidump/rust-minidump/tree/main/testdata

https://github.com/rust-minidump/rust-minidump/issues/786 ,help me to watch this
