### ISSUE TITLE
When using local debug information inline information appears to be wrong

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/rust-minidump#832]
I've tested unwinding local debug information with a local build of Firefox and the resulting stack traces have incoherent inlining information. It appears to be scattered all over the frames so it's likely that we're reading the inline information incorrectly. Here's how to reproduce:
- Make a local build of Firefox
- Generate symbol files with `./mach buildsymbols`
- Run Firefox with `./mach run --enable-crash-reporter`, browse to *about:crashcontent*
- Do not interact with the crash reporter UI, instead copy the minidump out of `~/.mozilla/firefox/Crash Reports/pending`
- Close firefox
- Unpack the archive with the symbol files that have been generated in Firefox' object dir under `dist/firefox-114.0a1.en-US.linux-x86_64.crashreporter-symbols.zip`
- Now run `minidump-stackwalk <minidump> <path_to_symbol_files>` and `minidump-stackwalk --use-local-debuginfo <minidump>`, compare the resulting output

`dump_syms` processes inline information (see [this](https://github.com/mozilla/dump_syms/blob/fa4caf72ff6ca07c0bbf29cecf693c6294193563/src/collector.rs#L164-L340)) so we most likely have to do the same to get coherent stacks between the two unwinders.

**Comment by afranchuk** [comment]
`symbolic-cfi` is supposed to handle inline functions too, but I'll reproduce and see if I need to tweak some things to get the two methods to match.

**Comment by afranchuk** [comment]
From manual inspection, it looks like the addresses are correct (they point to the last byte of the `call` instruction). Also with #835, the output of `minidump-stackwalk` using debuginfo is almost identical to the output using symbol files: it has a few extra, more accurate frames at the earliest frames of each trace, and it lacks the file hash that is displayed in the source info.
