### ISSUE TITLE
possible_bit_flips source_register is not documented in schema

### ISSUE THREAD

**Issue by willkg** [rust-minidump/rust-minidump#858]
This crash report:

https://crash-stats.mozilla.org/report/index/8ae4e0f4-bdfc-4eaf-a11c-9e9750230630#tab-rawdump

was processed with minidump-stackwalk 0.16.0 (2023-04-27 v0.16.0) and has this in the stackwalker output:

```
"possible_bit_flips": [
    {
        "address": "0x00007ffdaf60bf90",
        "confidence": 0.625,
        "details": {
            "is_null": false,
            "nearby_registers": 1,
            "poison_registers": false,
            "was_low": false,
            "was_non_canonical": false
        },
        "source_register": null
    },
...
```

The `source_register` isn't documented in the schema here:

https://github.com/rust-minidump/rust-minidump/blob/main/minidump-processor/json-schema.md

What does this field hold?

**Comment by gabrielesvelto** [comment]
It's the hardware register which contained the pointer. It's either empty (which means it's the crash address) or it's a string like `rax`, `ecx`, `r12`, etc... @afranchuk can you add this information to the schema please?

**Comment by afranchuk** [comment]
I hadn't intentionally added that to the output there (I just added it to the struct which is serialized); it's used in human-friendly CLI output. But I guess it doesn't hurt to include it in the JSON output.

**Comment by willkg** [comment]
Thank you!
