### ISSUE TITLE
Expose raw MINIDUMP_MEMORY_INFO in MinidumpMemoryInfo

### ISSUE THREAD

**Issue by poolspray** [rust-minidump/rust-minidump#860]
Hello - we are interested in fields such as allocation_base which have not been mapped to the MinidumpMemoryInfo struct, for compat, probably the easiest way is to expose the raw field.  Would it be possible to expose the raw MINIDUMP_MEMORY_INFO field as pub in the MinidumpMemoryInfo struct as seen here?  Thanks! https://github.com/rust-minidump/rust-minidump/blob/469f95c8feb0715ffb514f48945d33ab0038cfb3/minidump/src/minidump.rs#L251

**Comment by gabrielesvelto** [comment]
Works for me! Send a PR and I'll merge it

**Comment by poolspray** [comment]
Thanks, just did. https://github.com/rust-minidump/rust-minidump/pull/866

**Comment by poolspray** [comment]
@gabrielesvelto - we were curious when a next release may occur, saw that the last was in May.

**Comment by gabrielesvelto** [comment]
I'll cut a new release this week if time permits, or next week at the latest.

**Comment by pop-calc** [comment]
> I'll cut a new release this week if time permits, or next week at the latest.

Hi, just following up on next release date. Thanks!

**Comment by gabrielesvelto** [comment]
Working on it, sorry, some things got in the way

**Comment by gabrielesvelto** [comment]
The 0.18.0 is available on crates.io and the release flow on GH is running as I write this.
