### ISSUE TITLE
implement /code_file/code_id/sym_file symbol download attempt

### ISSUE THREAD

**Issue by willkg** [rust-minidump/rust-minidump#870]
In [bug 1746940](https://bugzilla.mozilla.org/show_bug.cgi?id=1746940), I changed the download API for the Mozilla Symbol Server such that it can handle `/code_file/code_id/sym_file` requests. If it has a record with that `code_file` / `code_id` combination, it'll return an HTTP 302 redirect to the relevant `/debug_file/debug_id/sym_file` url.

Records are created during symbol upload. For symbol files, Mozilla Symbol Server will parse the header consisting of `MODULE` and `INFO` lines and capture `debug_filename`, `debug_id`, `code_file`, `code_id`, and `generator` information. I need to figure out how to backfill the information. I'll probably do it item-by-item based on the missing symbols emails.

Anyhow, this is currently deployed to the stage environment. I'm planning to deploy it to the prod environment next week.

This issue covers changing the rust-minidump stackwalker to try downloading the symbol using `/code_file/code_id/sym_file` in the case where the debug filename and debug id are missing or bogus.

**Comment by willkg** [comment]
We can test this today using a xul.sym I uploaded to the stage environment.

Symbol file: https://symbols.stage.mozaws.net/uploads/files/file/71624

Crash report: [421408bf-aa63-4e5e-8af9-8ee3a0230907](https://crash-stats.mozilla.org/report/index/421408bf-aa63-4e5e-8af9-8ee3a0230907)

When the stackwalker processes the minidump for that crash report, it sees there's no debug file or debug id, so it doesn't download the symbol file for the xul module. When the stackwalker requests `/code_file/code_id/sym_file`, it'll get a redirect with the debug filename and debug id. It can follow that redirect to get to the symbol file just like it does now.

**Comment by willkg** [comment]
I was thinking I could tackle this.

I'd write an equivalent to `breakpad_sym_lookup` that uses `code_file` and `code_id`. Maybe call it `breakpad_sym_lookup_by_code_file_code_id`? Then I'd change this code:

https://github.com/rust-minidump/rust-minidump/blob/7cda551f9f082f8ba5a286f931b5ad24e34861d9/breakpad-symbols/src/http.rs#L204

so that if `breakpad_sym_lookup` didn't return a `FileLookup`, it'd try the new function to get a `FileLookup` and if that also failed, it'd return the `SymbolError::MissingDebugFileOrId`.

I think we only need to change the code around this one use of `breakpad_sym_lookup`. The other instances look like they're looking at a file system and not an HTTP symbol supplier.

Does that sound like a good approach?

**Comment by gabrielesvelto** [comment]
Yes, it's fine!

**Comment by willkg** [comment]
Not all http symbol suppliers will be able to do the lookup. Do we want to make the additional lookup optional and off by default?

**Comment by gabrielesvelto** [comment]
I'm not worried about that. Apart from Tecken the only other endpoint I can think of is whatever Google uses, and even there we'd be making an extra request only if the first one fails. The second one will also fail but I don't think it would cause a problem on the server-side, no?

**Comment by willkg** [comment]
So, this turned out to be a little harder to do because I really want a `symbol_url` with the `debug_filename` and `debug_identifier` in it and not the one with the `code_file` and `code_identifier` in it.

I got it working, but I'm mulling over fixing the module with the information returned from the lookup.

I'm testing with [421408bf-aa63-4e5e-8af9-8ee3a0230907](https://crash-stats.mozilla.org/report/index/421408bf-aa63-4e5e-8af9-8ee3a0230907).

Currently, the stackwalker outputs this:

```
{
    "base_addr": "0x69920000",
    "cert_subject": "Mozilla Corporation",
    "code_id": "64e782c570c4000",
    "corrupt_symbols": false,
    "debug_file": "",
    "debug_id": "000000000000000000000000000000000",
    "end_addr": "0x709e4000",
    "filename": "xul.dll",
    "loaded_symbols": false,
    "missing_symbols": true,
    "symbol_url": null,
    "version": "117.0.0.8636"
},
```

With my changes and using the symbols server staging environment, it now outputs this:

```
{
    "base_addr": "0x69920000",
    "cert_subject": null,
    "code_id": "64e782c570c4000",
    "corrupt_symbols": false,
    "debug_file": "",
    "debug_id": "000000000000000000000000000000000",
    "end_addr": "0x709e4000",
    "filename": "xul.dll",
    "loaded_symbols": true,
    "missing_symbols": false,
    "symbol_url": "https://symbols.stage.mozaws.net/xul.pdb/1BCB86F9A4FEEC254C4C44205044422E1/xul.sym?code_file=xul.dll&code_id=64e782c570c4000",
    "version": "117.0.0.8636"
},
```

Would it be better for the things that use this data to have the correct `debug_file` and `debug_id` filled in? I think it would, so I think we want to do that.

If we do that, do we want to capture the fact that we've found the information by doing a lookup using the code information in a flag? We've got `corrupt_symbols`, `loaded_symbols`, and `missing_symbols`. Maybe we also add `fixed_debug_info`?

**Comment by willkg** [comment]
I hit problems with the the code change and how it affects the disk cache, so I'm redoing my fix. Further, it's tricky to thread the correct `debug_file` and `debug_identifier` back, so I'm giving up on that and the `fixed_debug_info` flag for now.
