### ISSUE TITLE
How to parse symbols for Mac OS system libraries(eg:libqcocoa.dylib or libsystem_kernel.dylib) in minidump_stackwalk

### ISSUE THREAD

**Issue by marshalchan** [rust-minidump/rust-minidump#879]
How to obtain the symbol file of the macos system library? Is there a system library file symbol file that can automatically download the corresponding version by specifying srv * like Windbg?

**Comment by gabrielesvelto** [comment]
Unfortunately there is no such thing for macOS. What we do in Mozilla is manually scrape the system libraries and put them on our symbol server. Since it's public you can use it, try it with:
```
minidump-stackwalk --symbols-url https://symbols.mozilla.org
```
We have symbols for most versions of macOS starting with 10.12+

**Comment by marshalchan** [comment]
Thank you for your reply. Previously, I thought this symbol server was just a symbol file for Firefox browser. However, there is a problem. The stack file I parsed using the following command still cannot see any functions from the Mac OS system library:
./mimidump_stackwalk-intel 1.dmp --symbols-url https://symbols.mozilla.org ./symbols > 1.txt

**Comment by marshalchan** [comment]
@gabrielesvelto  Is there a problem with my usage?

**Comment by gabrielesvelto** [comment]
Then it's likely that we don't have that particular symbol on file. We have many but not all.

**Comment by marshalchan** [comment]
I would like to obtain the following results:
![image](https://github.com/rust-minidump/rust-minidump/assets/39484653/e5570260-3ef8-4d9f-a6c0-8ee63e7526cb)

The actual analysis results are as follows:
![image](https://github.com/rust-minidump/rust-minidump/assets/39484653/a715b82b-d1d2-402c-a1d7-af1dfd395659)

**Comment by marshalchan** [comment]
> Then it's likely that we don't have that particular symbol on file. We have many but not all.

That's probably the reason. Thank you again for your reply
